---
version: "3"
services:
  home-assistant:
    image: homeassistant/raspberrypi4-homeassistant:stable
    container_name: home-assistant
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
    volumes:
      - './config:/config'
    network_mode: "host"
    ports:
      - 8123:8123
    restart: unless-stopped
