---

version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "8443:443/tcp"
    dns:
      - "127.0.0.1"
      - "8.8.8.8"
    hostname: pihole
    memory: 512M
    environment:
      TZ: 'America/New_York'
      FTLCONF_LOCAL_IPV4: '192.168.1.10'
      TEMPERATUREUNIT: 'f'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './data/etc-pihole:/etc/pihole:Z'
      - './data/etc-dnsmasq.d:/etc/dnsmasq.d:Z'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
